categories:
  - title: 'Features :rocket:'
    labels: 
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes :bug:'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'invalid'
template: |
  ## Changes
  
  $CHANGES    
